# Copied to xiaoning.local.ps1 by setup.ps1. Never commit the local copy.
$env:XIAONING_LLM_API_BASE = __XIAONING_LLM_API_BASE__
$env:XIAONING_LLM_API_KEY = __XIAONING_LLM_API_KEY__
$env:XIAONING_LLM_MODEL = __XIAONING_LLM_MODEL__
$env:XIAONING_OUTBOUND_PROXY = ""
$env:NAPCAT_HTTP_TOKEN = ""
$env:ASTRBOT_DASHBOARD_INITIAL_PASSWORD = "__GENERATED_DASHBOARD_PASSWORD__"
$env:XIAONING_ENABLE_VOICE = "0"
$env:FIRESTORE_PROJECT = ""
$env:FIRESTORE_DATABASE = ""
$env:WEB_STUDIO_PROJECT = ""
$env:WEB_STUDIO_SITE = ""
$env:WEB_STUDIO_PUBLIC_ORIGIN = ""
$env:PUBLIC_CONTACT_EMAIL = ""
$env:PUBLIC_REVIEWER_ID = ""
$env:PUBLIC_SUMMARY_GROUP_ID = ""
$env:XIAONING_REPORT_EMAIL_TO = ""
$env:XIAONING_REPORT_SMTP_HOST = "smtp.gmail.com"
$env:XIAONING_REPORT_SMTP_PORT = "587"
$env:XIAONING_REPORT_SMTP_USERNAME = ""
# Use a provider-specific app password. Never commit the local value.
$env:XIAONING_REPORT_SMTP_PASSWORD = ""
